<?php

namespace Database\Factories;

use App\Modules\Events\Enums\EventStatus;
use App\Modules\Events\Models\Event;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<Event>
 */
class EventFactory extends Factory
{
    protected $model = Event::class;

    public function definition(): array
    {
        $start = fake()->dateTimeBetween('+1 month', '+3 months');

        return [
            'name' => fake()->unique()->company().' LAN '.fake()->year(),
            // slug intentionally omitted: generated by the Event::booted() creating-hook
            'status' => EventStatus::Draft,
            'location' => fake()->city(),
            'starts_at' => $start,
            'ends_at' => (clone $start)->modify('+2 days'),
            'max_participants' => fake()->numberBetween(50, 200),
            'settings' => [],
        ];
    }

    public function status(EventStatus $status): static
    {
        return $this->state(['status' => $status]);
    }

    public function draft(): static
    {
        return $this->status(EventStatus::Draft);
    }

    public function announced(): static
    {
        return $this->status(EventStatus::Announced);
    }

    public function registration(): static
    {
        return $this->status(EventStatus::Registration);
    }

    public function live(): static
    {
        return $this->status(EventStatus::Live);
    }

    public function finished(): static
    {
        return $this->status(EventStatus::Finished);
    }

    public function archived(): static
    {
        return $this->status(EventStatus::Archived);
    }
}
