<?php

namespace Database\Factories;

use App\Models\User;
use App\Modules\Events\Models\Event;
use App\Modules\Registration\Enums\RegistrationStatus;
use App\Modules\Registration\Models\EventRegistration;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<EventRegistration>
 */
class EventRegistrationFactory extends Factory
{
    protected $model = EventRegistration::class;

    public function definition(): array
    {
        return [
            'event_id' => Event::factory(),
            'user_id' => User::factory(),
            'ticket_type' => 'standard',
            'status' => RegistrationStatus::Confirmed,
            // qr_token intentionally omitted: generated by the creating hook
        ];
    }

    public function pending(): static
    {
        return $this->state(['status' => RegistrationStatus::Pending]);
    }

    public function cancelled(): static
    {
        return $this->state(['status' => RegistrationStatus::Cancelled]);
    }

    public function paid(): static
    {
        return $this->state(['paid_at' => now()]);
    }

    public function checkedIn(): static
    {
        return $this->state(['checked_in_at' => now()]);
    }
}
