<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::table('server_links', function (Blueprint $table): void {
            // The per-server bearer credential a CS2 game server (MatchZy/
            // G5API) presents to authenticate its telemetry webhook POSTs
            // (Task 12 — see MatchTelemetryController). Never client-
            // fillable: lazily generated by ServerLink's `creating` model
            // event (see ServerLink::booted()), mirroring status/join_info's
            // "state, not input" treatment. Nullable only because existing
            // rows created before this migration have none; every row
            // created from here on gets one.
            $table->string('telemetry_token')->nullable()->after('status');
        });
    }

    public function down(): void
    {
        Schema::table('server_links', function (Blueprint $table): void {
            $table->dropColumn('telemetry_token');
        });
    }
};
